name: ffaclasses
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.4
  email_validator: ^2.0.1
  firebase_auth: ^3.1.4
  flex_color_scheme: ^4.1.1
  flutter:
    sdk: flutter
  flutter_pw_validator: ^1.3.0
  flutter_riverpod: ^1.0.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  invoiceninja: ^0.0.9
  path_provider: ^2.0.7
  table_calendar: ^3.0.3
  time_range: ^1.0.2
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  hive_generator: ^1.1.1
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
