name: ffaclasses
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.4
  email_validator: ^2.0.1
  firebase_auth: ^3.1.4
  flutter:
    sdk: flutter
  flutter_pw_validator: ^1.3.0
  flutter_riverpod: ^1.0.0
  table_calendar: ^3.0.3
  time_range: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
